#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns64"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/DomePlugIns/"

cp "/tmp/ACEDome_X2/domelist ACEDome.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/ACEDome_X2/ACEDome.ui" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/ACEDome_X2/ACE.png" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/ACEDome_X2/libACEDome.dylib" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist ACEDome.txt"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/ACEDome.ui"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/ACE.png"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/libACEDome.dylib"
fi
chmod 644 "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist ACEDome.txt"
chmod 755 "$PLUGINS_DIR/DomePlugIns/libACEDome.dylib"
chmod 644 "$PLUGINS_DIR/DomePlugIns/ACEDome.ui"
chmod 644 "$PLUGINS_DIR/DomePlugIns/ACE.png"
rm -rf /tmp/ACEDome_X2
